Creta Active record model
ioilmio/microreddit pull request #1
Opened 2020-07-13 17:31 UTC by ioilmio

This creates model for user comment and post;
Add basic validations for those resources.

2020-07-14 00:04 UTC, uryelah commented
Hi **Salvo Illuminato**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with this project, you are just missing one relation between the user and comment. Check the required changes below and good coding! 💪 

# Required Changes 🏗️ 🐛 💡

- [ ] A user can write more than one comment and a comment can only have one user author, right? Make sure that you associate the comment and user model accordingly, who belongs to who and who has many of the other?

-----

 **Kindly fix the pointed out issues before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-07-15 12:59 UTC, uryelah requested changes
Hi Salvo, you are almost there. 
Just make sure to follow the rails conventions, I left I comment in your code with the issue you need to fix.

# Required Changes 🏗️ 🐛 💡

2020-07-15 12:59 UTC, uryelah commented on app/models/comment.rb
> +  belongs_to :user_id
- [ ] It shoud belong to :user (as in the User model), not user_id.

2020-07-15 13:01 UTC, uryelah commented on app/models/comment.rb
> +  belongs_to :user_id
- [ ] Also, if it belongs to one it should be :post, in the singular.

2020-07-15 13:01 UTC, uryelah commented on app/models/comment.rb
> +  belongs_to :user_id
https://guides.rubyonrails.org/association_basics.html#the-belongs-to-association

2020-07-16 00:55 UTC, rOluochKe approved these changes
Hello Team!
### Well done, you got it right this time :clap: The project has been approved. Congratulations :boom: :100:
### Merge the project and submit it. Good luck with the next one!

- Happy coding!

2020-07-16 01:59 UTC, merged